[package]
name = "wasabi-liquid-native-transaction-validation"
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
license = "MIT"
publish = false
description = "Transaction amount-proof validation for Wasabi Liquid"

[dependencies]
elements = { git = "https://github.com/liquid-wasabi/rust-elements.git", rev = "aeed87e94d3f5dd429a55c16492dca24b5fac16f", default-features = false }
wasabi-liquid-native-output-opening = { path = "../output-opening" }
