[package]
name = "wasabi-liquid-native-transaction-validation"
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
license = "MIT"
publish = false
description = "Transaction amount-proof validation for Wasabi Liquid"

[dependencies]
elements = { git = "https://github.com/liquid-wasabi/rust-elements.git", rev = "0d7647ca90c568c36a0d6fbb30f61291dfcafdb2", default-features = false }
wasabi-liquid-native-output-opening = { path = "../output-opening" }

[dev-dependencies]
rand = "0.8"
