[package]
name = "wasabi-liquid-native-transaction-validation"
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
license = "MIT"
publish = false
description = "Transaction amount-proof validation for Wasabi Liquid"

[dependencies]
elements = { git = "https://github.com/liquid-wasabi/rust-elements.git", rev = "d1f8850a046487cb27c911d5c6e71851b2a989fd", default-features = false }
wasabi-liquid-native-output-opening = { path = "../output-opening" }
